POST http://127.0.0.1:8000/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "tinni1",
    "email": "tinni1@gmail.com",
    "first_name": "Tasnim Afrose",
    "last_name": "Tinni",
    "password": "admin123@",
    "password2": "admin123@"
}

###
POST http://127.0.0.1:8000/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"kaniz@gmail.com",
    "password":"admin123@"
}


###
POST http://127.0.0.1:8000/api/groups/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MzI1NzM1LCJpYXQiOjE3ODkzMjU0MzUsImp0aSI6ImZjMTBkMDYxYTk0NjRlMTk5NmI5YzU4NTMzNDliZGIzIiwidXNlcl9pZCI6IjIifQ.6qP2SR9sYNK1i-nBzmWMInYTk5UST6KjMFHJgl8z1Uk

{    
    "name":"Sylhet Border Hiking"
}


###

POST http://127.0.0.1:8000/api/groups/1/members/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MzI1ODYxLCJpYXQiOjE3ODkzMjU1NjEsImp0aSI6IjI2NmEzNTFhYWQwNTQyZjI4NDY0OTg1Yjc0OTU2OTg1IiwidXNlcl9pZCI6IjMifQ.mDAUpwgW2HSaasYwQhdXh-X1evEdlgrBd13OjUXrZl4

{    
    "username":"tinni"
}

###
GET http://127.0.0.1:8000/api/groups/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MzI2MTE5LCJpYXQiOjE3ODkzMjU4MTksImp0aSI6IjExZTM0NDljMzBjODRiZmY5YjQ0ZTE2Yzk1MGVmYzk3IiwidXNlcl9pZCI6IjIifQ.BV3k0G2l_o-OPP6savhtaM7EMqtamG9E5VO5V7Z9Z5w


###
POST http://127.0.0.1:8000/api/groups/1/expenses/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MzI2MTE5LCJpYXQiOjE3ODkzMjU4MTksImp0aSI6IjExZTM0NDljMzBjODRiZmY5YjQ0ZTE2Yzk1MGVmYzk3IiwidXNlcl9pZCI6IjIifQ.BV3k0G2l_o-OPP6savhtaM7EMqtamG9E5VO5V7Z9Z5w

{    
    "paid_by": 2,
    "amount": "3000.00",
    "description": "lauch"

}

###
GET http://127.0.0.1:8000/api/groups/1/expenses/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MzIyMTEyLCJpYXQiOjE3ODkzMjE4MTIsImp0aSI6ImYwM2U5ODYyNGQ4NzQ5M2I5MTM5NTRlZWEyYmI0YWRhIiwidXNlcl9pZCI6IjIifQ.fHPhGAWoEYjp29xeUmKtLMrFIJBe0_FVimbBupKuDf0

###
PUT http://127.0.0.1:8000/api/groups/1/expenses/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MzI2OTA2LCJpYXQiOjE3ODkzMjY2MDYsImp0aSI6ImIyN2ZlZmMxODU5OTRiMzY4YjI1MDJlY2I2ZGNmNWVhIiwidXNlcl9pZCI6IjIifQ._FTTP4fNZL1zJhr_lvNu_SUllTlNgH8lFRYmY1LF2oE

{    
    "paid_by": 2,
    "amount": "5000.00",
    "description": "lauch"

}