@baseUrl = http://127.0.0.1:8000
@accessToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5NDExMDQ0LCJpYXQiOjE3ODk0MDkyNDQsImp0aSI6IjI1YWEyOGM3ODg4ZTQ1M2M4M2U2Y2YxNTQ4NzU1ZjgwIiwidXNlcl9pZCI6IjQifQ.d_yD2ErO5E5lAo6O5ZqTy0L6QdJSZqBuKhT15qGVc8w
### Register
POST {{baseUrl}}/auth/register/
Content-Type: application/json

{
    "username": "tinni1",
    "email": "tinni1@gmail.com",
    "first_name": "Tasnim Afrose",
    "last_name": "Tinni",
    "password": "admin123@",
    "password2": "admin123@"
}


### Login
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "tinni1@gmail.com",
    "password": "admin123@"
}


### Create Group
POST {{baseUrl}}/api/groups/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Jaflong Tour 2"
}

###  Group list
GET {{baseUrl}}/api/groups/
Content-Type: application/json
Authorization: Bearer {{accessToken}}



### Add Member
POST {{baseUrl}}/api/groups/2/members/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "username": "tinni1"
}


### Get Group
GET {{baseUrl}}/api/groups/3/
Authorization: Bearer {{accessToken}}

### remove member from perticular group
DELETE http://127.0.0.1:8000/api/groups/2/members/2/
Authorization: Bearer {{accessToken}}

### Create Expense
POST {{baseUrl}}/api/groups/1/expenses/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "paid_by": 2,
    "amount": "3000.00",
    "description": "lauch"
}


### Get Expense
GET {{baseUrl}}/api/groups/1/expenses/
Authorization: Bearer {{accessToken}}


### Update Expense
PUT {{baseUrl}}/api/groups/1/expenses/3/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "paid_by": 2,
    "amount": "5000.00",
    "description": "lauch"
}